# Generated by Django 3.1.1 on 2021-01-29 18:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goldenShoe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_ID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
