# Generated by Django 3.1.1 on 2021-01-29 18:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goldenShoe', '0002_auto_20210129_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order_ID',
        ),
        migrations.RemoveField(
            model_name='product',
            name='order_trans_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='order_trans_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
