# Generated by Django 3.1.1 on 2021-02-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldenShoe', '0003_auto_20210129_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Sport', 'Sport'), ('Smart', 'Smart'), ('Slipper', 'Slipper'), ('Heel', 'Heel')], default='Smart', max_length=10),
        ),
    ]
