# Generated by Django 3.1.1 on 2021-02-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldenShoe', '0004_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Yellow', 'Yellow'), ('Black', 'Black'), ('Blue', 'Blue'), ('Pink', 'Pink'), ('Brown', 'Brown'), ('Green', 'Green'), ('Fucsia', 'Fucsia'), ('Orange', 'Orange'), ('Grey', 'Grey'), ('Peach', 'Peach'), ('Amber', 'Amber'), ('White', 'White')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default=9, max_length=10),
        ),
    ]
