# Generated by Django 2.1.3 on 2018-11-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='hobbies',
            field=models.ManyToManyField(blank=True, related_name='related_to', to='matchapp.Hobby'),
        ),
    ]
