# Generated by Django 2.1.3 on 2018-11-17 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchapp', '0002_auto_20181117_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hobby',
        ),
    ]
