# Generated by Django 2.1.3 on 2018-11-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchapp', '0002_auto_20181120_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(max_length=8, null=True),
        ),
    ]
